version: "3.7"
services:
  mongo:
    image: mongo:latest
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - /data/RCS/mongo:/data/db
    command: --wiredTigerCacheSizeGB 1.5
    hostname: yvo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'RCSAccess'
      MONGO_INITDB_ROOT_PASSWORD_FILE: '/run/secrets/mongo_pass'
    ports:
      - "27017:27017"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    secrets:
      - mongo_pass

secrets:
  mongo_pass:
    file: /etc/RCS/mongo_pass
