version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_BUILD_NUMBER)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Access/Dockerfile -t IMAGE_REPO_NAME  .
      - docker build -f DataProcessor/Dockerfile -t IMAGE_REPO_NAME-DP .
      - docker build -f RuleEngine/Dockerfile -t IMAGE_REPO_NAME-REG .

      - docker tag $IMAGE_REPO_NAME $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME-DP $IMAGE_REPO_NAME-DP:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME-REG $IMAGE_REPO_NAME-REG:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $IMAGE_REPO_NAME-DP:$IMAGE_TAG
      - docker push $IMAGE_REPO_NAME-REG:$IMAGE_TAG
      - echo Writing image definitions file...