version: "3.7"
services:
  rabbit:
    image: rabbitmq:3-management-alpine
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - /data/RCS/rabbitmq:/var/lib/rabbitmq
    hostname: yvo
    environment:
      RABBITMQ_DEFAULT_USER: 'RCSAccess'
      RABBITMQ_DEFAULT_PASS_FILE: '/run/secrets/rabbit_pass'
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    secrets:
      - rabbit_pass

secrets:
  rabbit_pass:
    file: /etc/RCS/rabbit_pass
